"""Which seed file holds which table. One place, so every tool agrees."""
SEED_FILES = [
    ("seed/languages.csv", "Languages"),
    ("seed/roles.csv", "Roles"),
    ("seed/units.csv", "Units"),
    ("seed/disciplines.csv", "Disciplines"),
    ("seed/activity_types.csv", "ActivityTypes"),
    ("seed/document_types.csv", "DocumentTypes"),
    ("seed/data_classifications.csv", "DataClassifications"),
    ("seed/residency_requirements.csv", "ResidencyRequirements"),
    ("seed/tax_rules.csv", "TaxRules"),
    ("seed/legal_entities.csv", "LegalEntities"),
    ("seed/numbering_series.csv", "NumberingSeries"),
    ("seed/document_templates.csv", "DocumentTemplates"),
    ("seed/materials.csv", "Materials"),
    ("seed/synthetic_projects/clients.csv", "Clients"),
    ("seed/synthetic_projects/contacts.csv", "Contacts"),
    ("seed/synthetic_projects/users.csv", "Users"),
    ("seed/synthetic_projects/projects.csv", "Projects"),
    ("seed/synthetic_projects/project_assignments.csv", "ProjectAssignments"),
    ("seed/synthetic_projects/locations.csv", "Locations"),
    ("seed/synthetic_projects/project_activity_rules.csv", "ProjectActivityRules"),
    ("seed/synthetic_projects/approval_matrix.csv", "ApprovalMatrix"),
    ("seed/synthetic_projects/approval_delegations.csv", "ApprovalDelegations"),
    ("seed/synthetic_projects/residency_assignments.csv", "ResidencyAssignments"),
    ("seed/synthetic_projects/contracts.csv", "Contracts"),
    ("seed/synthetic_projects/boq_items.csv", "BOQItems"),
    ("seed/synthetic_projects/site_visits.csv", "SiteVisits"),
    ("seed/synthetic_projects/visit_activities.csv", "VisitActivities"),
    ("seed/synthetic_projects/photos.csv", "Photos"),
    ("seed/synthetic_projects/snags.csv", "Snags"),
    ("seed/synthetic_projects/temporary_access_grants.csv", "TemporaryAccessGrants"),
    ("seed/synthetic_projects/system_recovery_plan.csv", "SystemRecoveryPlan"),
]
